### PR TITLE
Update Python version support.

### PR DESCRIPTION
**Pull request by icemac**
- **Drop support for Python 3.7.**
- **Add support for Python 3.12, 3.13.**
- **Configuring for pure-python**
- **Update Python version support.**

I had to add `"legacy-cgi; python_version >= '3.13'"` because `WebOb` still uses `cgi` module which is gone in 3.13.

### CODE REVIEW

**Review by dataflake — APPROVED** [review]
Just out of curiosity, what is this old stuff still used for?

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2024-10-17 00:39 -0700:
>Just out of curiosity, what is this old stuff still used for?

For example in the tests of `zope.app.form`
(and when I remember right, `zope.app.form` provides widgets
for `zope.formlib`).

**Comment by dataflake** [comment]
Thank you Diter, I had no idea...

**Comment by icemac** [comment]
No, `zope.app.form` no longer provides the wigets for `zope.formlib`, they have been moved into `zope.formlib` already in 2010. But there are still some packages which depend on `zope.app.form` for other features, so I was not able to archive it so easily.

**Comment by icemac** [comment]
Thank you for reviewing this PR. 😃

**Pull request merged**
